### PR TITLE
Update CSB and brokerpak versions

### PR DESCRIPTION
**Pull request by mogul**
The tests won't pass until [this PR](https://github.com/GSA/datagov-brokerpak-solr/pull/27) is merged and a `v1.0.2` release tag is pushed to `datagov-brokerpak-solr`, but I wanted to at least get this PR started as a draft so it can be approved code-wise, and then the tests can be rerun ASAP.

Related to https://github.com/GSA/datagov-deploy/issues/3504

### CODE REVIEW

**Comment by mogul** [comment]
Also, please leave this in the draft+unmerged state until I get a chance to test it in the dev environment... I suspect `datagov-brokerpak-smtp` will need some additional environment variables set.

**Comment by nickumia-reisys** [comment]
I pushed the `v1.0.2` tag to the `datagov-brokerpak-solr` repo and the release passed.

**Comment by mogul** [comment]
Testing this in the `development` space, I'm hitting a wall where the broker appears to hand back broken JSON for a Terraform state, resulting in errors like `delete could not be completed: Service instance ssb-solr-k8s: Service broker error: unexpected end of JSON input`. 

I suspect this is due to [the problem described here](https://github.com/cloudfoundry-incubator/cloud-service-broker/pull/321), which might result in truncation of a TF state when it's stored in the database. I've asked about this [in the CSB Slack channel](https://cloudfoundry.slack.com/archives/C0164KKEZGX/p1635907093002100), and whether another version is imminent.

**Comment by mogul** [comment]
CSB upstream has just released [0.4.1](https://github.com/cloudfoundry-incubator/cloud-service-broker/releases/tag/0.4.1) that addresses this problem. We'll need to run that through PRs in our various repositories and this branch today.

**Comment by mogul** [comment]
I've confirmed successful deployment with 0.4.1 in `development`. I'm going to trigger the tests again in order to generate new Terraform plans. (We should see the `ssb-solr` app and `ssb-solr-k8s` service included in the plans; I explicitly nuked those to ensure their recreation.)

**Comment by mogul** [comment]
I'm a little concerned that I don't see the re-creation of the ssb-solr-k8s` service in the prod plan, but I'm going to stand by and be prepared to address that manually if it doesn't apply properly. Here goes nothing!

**Review by jbrown-xentity — APPROVED** [review]

**Comment by mogul** [comment]
> I'm a little concerned that I don't see the re-creation of the `ssb-solr-k8s` service in the prod plan, but I'm going to stand by and be prepared to address that manually if it doesn't apply properly. Here goes nothing!

I feel like a fortune teller! The plan didn't apply in `prod` because the apply also turned up the need to create the `ssb-solr-k8s` service, as you can see [here](https://github.com/GSA/datagov-ssb/runs/4111242440?check_suite_focus=true#step:5:289). I'm going to apply manually.

**Pull request merged**
