### PR TITLE
Terraform driven eks deploy alternative providers

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Replaces https://github.com/GSA/datagov-ssb/pull/122

### CODE REVIEW

**Comment by mogul** [comment]
After unwinding more state inadvertently tied to the wrong workspace, I was able to apply the current code (from this branch and the corresponding branch in datagov-brokerpak-eks) manually.

To get this far I've commented out the resources that aren't yet working. In particular, we still need to resolve the fact that the bind module is trying to configure the k8s provide; as a module that depends_on another module, it's not allowed to do that. I suspect the solution will be to have both the provision and binding happen in a single module.

**Comment by mogul** [comment]
We are not properly escaping the kubeconfig in order to [include it in the JSON being fed into the user-provided service creation](https://github.com/GSA/datagov-ssb/blob/68b93adb9e629c94b729e865c54d5c1ec020b83c/application-boundary.tf#L73).
```
$ docker-compose --env-file=.env.${ENV_NAME}.secrets run --rm terraform apply -var-file=terraform.${ENV_NAME}.tfvars
[...a lot of refreshing later...]
╷
│ Error: "credentials_json" contains an invalid JSON: invalid character '\n' in string literal
│ 
│   with cloudfoundry_user_provided_service.ssb-solrcloud-k8s,
│   on application-boundary.tf line 66, in resource "cloudfoundry_user_provided_service" "ssb-solrcloud-k8s":
│   66: resource "cloudfoundry_user_provided_service" "ssb-solrcloud-k8s" {

I got cross-eyed staring at this, but I bet @nickumia-reisys can figure it out.

**Comment by mogul** [comment]
Oh, and: [the GitHub Action doesn't have `aws-iam-authenticator` installed](https://github.com/GSA/datagov-ssb/runs/5371666619?check_suite_focus=true#step:6:276).

**Comment by mogul** [comment]
[Apparently there's now a `TERRAFORM_PRE_RUN` variable](https://github.com/dflook/terraform-github-actions/issues/57#issuecomment-886048155) that can help us with installing `aws-iam-authenticator`!

**Comment by mogul** [comment]
[Documentation on `TERRAFORM_PRE_RUN`.](https://github.com/dflook/terraform-github-actions/blob/master/terraform-apply/README.md#environment-variables)

**Review by robert-bryson — APPROVED** [review]

**Pull request merged**
