### PR TITLE
Bump the EKS brokerpak version

### PR DESCRIPTION
**Pull request by mogul**

### CODE REVIEW

**Comment by adborden** [comment]
This looks good to me, but I'm noticing:
```
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
      ~ catalog_change                   = true -> false
```

which has given us grief before.

**Review by adborden — APPROVED** [review]

**Comment by mogul** [comment]
Pretty sure that should work.

**Comment by mogul** [comment]
OK, something weird happened because the ssb-solr app already exists... I nuked it but now the plan differs. Sooooo... a replan PR is imminent.

**Comment by adborden** [comment]
Yeah, that is strange. Since terraform thinks it does not exist, that would imply it was removed from the TF state. Could that be a bug in the Cloud Foundry provider? Is it possible we manually removed it during debugging since the last deploy?

Let's keep an eye out for this issue in the future. The CF provider is still a bit beta (in that we've hit several issues with it over the course of the project), but let's see if we can provide a report in this.

**Comment by mogul** [comment]
Agreed!

**Pull request merged**
