### PR TITLE
Enable EKS broker to configure AWS SSM

### PR DESCRIPTION
**Pull request by mogul**
Necessary to enable https://github.com/GSA/data.gov/issues/3752

### CODE REVIEW

**Comment by mogul** [comment]
Looks like we need to unwind this branch now @nickumia-reisys ...
https://github.com/GSA/datagov-ssb/pull/131

**Comment by mogul** [comment]
(I suspect that's as easy as running an apply with the current content of `main` on the dev and staging workspaces, but I'm headed to bed now.)

**Comment by mogul** [comment]
(Or maybe updating the lock file? Dunno. ZZZZZZzzzzz...)

**Review by nickumia-reisys — APPROVED** [review]
Verified with Cloudtrail, these are the only API Calls that Terraform makes 🛎️

**Comment by nickumia-reisys** [comment]
Github! You are not working normally 😞 
image

**Review by nickumia-reisys — APPROVED** [review]
🛎️ 🛎️

**Pull request merged**
