### PR TITLE
update: solr brokerpak for solr auth

### PR DESCRIPTION
**Pull request by nickumia-reisys**
Related to https://github.com/GSA/datagov-deploy/issues/3523

### CODE REVIEW

**Comment by mogul** [comment]
We need to be _very careful_ when we roll this one out in order to avoid b0rking the inventory Solr instances in staging and prod! So don't merge this until we've done the up front work to prevent that.

**Comment by nickumia-reisys** [comment]
Proposed next steps:
- [ ] Update catalog solr [`service-config.json`](https://github.com/GSA/catalog.data.gov/blob/main/solr/service-config.json#L3) to point to `6-curl`
- [ ] Update inventory solr [`service-config.json`](https://github.com/GSA/inventory-app/blob/main/solr/service-config.json#L3) to point to `6-curl`
- [ ] Update current catalog solr services to use new image, `cf update-service catalog-solr -c '{"solrImageTag":"6-curl"}'`
  - [ ] Run in `staging`
  - [ ] Run in `prod`
- [ ] Update current inventorysolr services to use new image, `cf update-service inventory-solr -c '{"solrImageTag":"6-curl"}'`''
  - [ ] Run in `staging`
  - [ ] Run in `prod`
- [ ] Deploy this PR
- [ ] Test that provisioned creds for a brokered solr in staging now work

**Comment by nickumia-reisys** [comment]
@mogul 😟 I'm just going to leave this here..  I may or may not have broke something.  😢 

I tried to deploy the updates manually to the development space `ENV_NAME=development`.  I followed the steps in the datagov-ssb (this repo) README, recalling everything we had done in the past.  The last step, `docker-compose --env-file=.env.${ENV_NAME}.secrets run --rm terraform apply -var-file=terraform.${ENV_NAME}.tfvars` seemed okay when I ran it,
<details>
    <summary> Terraform plan </summary>

  ```
    Note: Objects have changed outside of Terraform
    Terraform detected the following changes made outside of Terraform since the last "terraform apply":
    
       module.broker_solr.cloudfoundry_app.ssb has been changed
      ~ resource "cloudfoundry_app" "ssb" {
            id                         = "6e797682-6f7c-40b1-8c95-8ca29f60ab37"
            name                       = "ssb-solr"
            # (20 unchanged attributes hidden)
    
          ~ service_binding {
              + params           = (sensitive value)
                # (1 unchanged attribute hidden)
            }
          ~ service_binding {
              + params           = (sensitive value)
                # (1 unchanged attribute hidden)
            }
            # (1 unchanged block hidden)
        }
      # module.broker_smtp.cloudfoundry_app.ssb has been changed
      ~ resource "cloudfoundry_app" "ssb" {
            id                         = "6746d6e7-92a5-4aa8-96f0-313be1aee3dc"
            name                       = "ssb-smtp"
            # (20 unchanged attributes hidden)
  
          ~ service_binding {
              + params           = (sensitive value)
                # (1 unchanged attribute hidden)
            }
            # (1 unchanged block hidden)
        }
    Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or
    respond to these changes.
  
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

    Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
      ~ update in-place
    
    Terraform will perform the following actions:
    
      # module.broker_eks.cloudfoundry_app.ssb will be updated in-place
      ~ resource "cloudfoundry_app" "ssb" {
            id                         = "884bc753-7e2e-4686-aeff-f2357ad4e2f9"
          ~ id_bg                      = "884bc753-7e2e-4686-aeff-f2357ad4e2f9" -> (known after apply)
            name                       = "ssb-eks"
          ~ source_code_hash           = "oFIHz3KGgRHHwrHWFCy07jNbdXth2GAsz7EckLc7jR8=" -> "R5AiOn6HjUOpoa1ci8ippf7hjtwdSPExzNCX/Spyi8s="
            # (18 unchanged attributes hidden)
            # (2 unchanged blocks hidden)
        }
    
      # module.broker_smtp.cloudfoundry_app.ssb will be updated in-place
      ~ resource "cloudfoundry_app" "ssb" {
            id                         = "6746d6e7-92a5-4aa8-96f0-313be1aee3dc"
          ~ id_bg                      = "6746d6e7-92a5-4aa8-96f0-313be1aee3dc" -> (known after apply)
            name                       = "ssb-smtp"
          ~ source_code_hash           = "BwKQ3ow7LiOCPMDdb12WMzub3jTiPWnZ3Y9GlQaOYjk=" -> "ugP4q5OY3byNJtGmsC8I44ugfiql7gbROeWYClJfQE4="
            # (18 unchanged attributes hidden)
    
    
            # (2 unchanged blocks hidden)
        }
    
      # module.broker_solr.cloudfoundry_app.ssb will be updated in-place
      ~ resource "cloudfoundry_app" "ssb" {
            id                         = "6e797682-6f7c-40b1-8c95-8ca29f60ab37"
          ~ id_bg                      = "6e797682-6f7c-40b1-8c95-8ca29f60ab37" -> (known after apply)
            name                       = "ssb-solr"
          ~ source_code_hash           = "XiYr3BX9sxZDqxn59BFZ5FCtHcIdmnlBOjcJlB6gz+I=" -> "yDIffUilZNGObsvWlHvP/6yF5GfJ5C/TIv/uqrHUhFM="
            # (18 unchanged attributes hidden)
            # (3 unchanged blocks hidden)
        }
    
    Plan: 0 to add, 3 to change, 0 to destroy.
    
    Do you want to perform these actions in workspace "development"?
      Terraform will perform the actions described above.
      Only 'yes' will be accepted to approve.
    
      Enter a value: yes
    
    module.broker_solr.cloudfoundry_app.ssb: Modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37]
    module.broker_eks.cloudfoundry_app.ssb: Modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9]
    module.broker_smtp.cloudfoundry_app.ssb: Modifying... [id=6746d6e7-92a5-4aa8-96f0-313be1aee3dc]
    module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 10s elapsed]
    module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 10s elapsed]
    module.broker_smtp.cloudfoundry_app.ssb: Still modifying... [id=6746d6e7-92a5-4aa8-96f0-313be1aee3dc, 10s elapsed]
```
</details>

After a while, terraform just errored with the follow,
<details>
<summary> Terraform Progress </summary>

```
module.broker_smtp.cloudfoundry_app.ssb: Still modifying... [id=6746d6e7-92a5-4aa8-96f0-313be1aee3dc, 6m30s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 6m30s elapsed]
module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 6m30s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 6m40s elapsed]
module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 6m40s elapsed]
module.broker_smtp.cloudfoundry_app.ssb: Still modifying... [id=6746d6e7-92a5-4aa8-96f0-313be1aee3dc, 6m40s elapsed]
module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 6m50s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 6m50s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 7m0s elapsed]
module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 7m0s elapsed]
module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 7m10s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 7m10s elapsed]
module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 7m20s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 7m20s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 7m30s elapsed]
module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 7m30s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 7m40s elapsed]
module.broker_solr.cloudfoundry_app.ssb: Still modifying... [id=6e797682-6f7c-40b1-8c95-8ca29f60ab37, 7m40s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 7m50s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 8m0s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 8m10s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 8m20s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 8m30s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 8m40s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 8m50s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 9m0s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 9m10s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 9m20s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 9m30s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 9m40s elapsed]
module.broker_eks.cloudfoundry_app.ssb: Still modifying... [id=884bc753-7e2e-4686-aeff-f2357ad4e2f9, 9m50s elapsed]
╷
│ Error: Timeout of 1m0s reached

[...]

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

Terraform crashed! This is always indicative of a bug within Terraform.
A crash log has been placed at "crash.953916863.log" relative to your current
working directory. It would be immensely helpful if you could please
report the crash with Terraform[1] so that we can fix this.

When reporting bugs, please include your terraform version. That
information is available on the first line of crash.log. You can also
get it by running 'terraform --version' on the command line.

SECURITY WARNING: the "crash.953916863.log" file that was created may contain
sensitive information that must be redacted before it is safe to share
on the issue tracker.

[1]: https://github.com/hashicorp/terraform/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! TERRAFORM CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: 1
```
</details>

I have the crash log.  We can review it when you get back.  I have little bit of hope that nothing important is broken because this was just the development space.. but I don't entirely understand if this could adversely impact the other spaces.

I wanted to deploy it to development to provision a solr instance to see if the credentials were fixed.  But I'm not sure what caused this to fail and if this PR will have the same issue.  You'll see in the logs above that SMTP and SOLR stop saying `still modifying`, but they don't say `creation complete` either, so I don't know what happened there.

P.S. The crash log is 44K Lines of output

**Comment by mogul** [comment]
I picked up where @nickumia-reisys left off, and deployed `datagov-ssb` to the development environment. The plan for me included just one change, updating the `ssb-solr` app, and it succeeded without crashing. (I have seen Terraform crashes be unrepeatable in the past.) 

I created an instance with no parameters, and then tried to create a key:
```bash
$ cf create-service solr-cloud base solr8test -b ssb-solr-gsa-datagov-development
[wait, completes successfully]
```

Then I tried creating a key for it, but it failed because `curl` wasn't in the Solr image:

```bash
$ cf create-service-key solr8test key
Creating service key key for service instance solr8test as bret.mogilefsky@gsa.gov...
Job (44590ced-21d5-4e24-b293-d423c3b4ecd5) failed: bind could not be completed: Service broker error: error performing bind: error from job runner: Error: Error running command 'kubectl --kubeconfig <(echo $KUBECONFIG | base64 -d) exec solr-105a845286c59f3c-solrcloud-0 --  curl \  -s -f -L \  -o /dev/null \  -w "%{http_code}\n" \  --user admin:${ADMIN_PASSWORD} \  'http://solr-105a845286c59f3c-solrcloud-common/solr/admin/authentication' \  -H 'Content-type:application/json' --data "$CREATE_USER_JSON"kubectl --kubeconfig <(echo $KUBECONFIG | base64 -d) exec solr-105a845286c59f3c-solrcloud-0 --  curl \  -s -f -L \  -o /dev/null \  -w "%{http_code}\n" \  --user admin:${ADMIN_PASSWORD} \  'http://solr-105a845286c59f3c-solrcloud-common/solr/admin/authorization' \  -H 'Content-type:application/json' --data "$SET_ROLE_JSON"': exit status 1. Output: Defaulted container "solrcloud-node" out of: solrcloud-node, cp-solr-xml (init), setup-zk (init)error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "6fd0d2a6ea61add98fefdeac86925e38a62e0546268fd8c715a840a97348fb26": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "curl": executable file not found in $PATH: unknownDefaulted container "solrcloud-node" out of: solrcloud-node, cp-solr-xml (init), setup-zk (init)error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "f741c6cf0e80e3550d5fb75cce836cb508557df1138a040a77b5f03f18d31a80": OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "curl": executable file not found in $PATH: unknown exit status 1
FAILED
```

I'd seen other work to add curl to the Solr image created for catalog, so I tried making an instance with that image. `curl` was present so I got further, but still got an error:

```bash
$ cf create-service solr-cloud base solr8test -b ssb-solr-gsa-datagov-development --wait -c '{"solrImageRepo":"ghcr.io/gsa/catalog.data.gov.solr", "solrImageTag":"8-curl"}'
Creating service instance solr8test in org gsa-datagov / space development as bret.mogilefsky@gsa.gov...

Waiting for the operation to complete..................................................................................

Service instance solr8test created.
OK

bmogilefsky@rocinante-w10:~/Documents/Code/datagov-ssb$ cf create-service-key solr8test keyCreating service key key for service instance solr8test as bret.mogilefsky@gsa.gov...
Job (133a1d40-231b-45c2-9acf-9d2f3cc657c0) failed: bind could not be completed: Service broker error: error performing bind: error from job runner: Error: Error running command 'kubectl --kubeconfig <(echo $KUBECONFIG | base64 -d) exec solr-03bc977ae38d1796-solrcloud-0 --  curl \  -s -f -L \  -o /dev/null \  -w "%{http_code}\n" \  --user admin:${ADMIN_PASSWORD} \  'http://solr-03bc977ae38d1796-solrcloud-common/solr/admin/authentication' \  -H 'Content-type:application/json' --data "$CREATE_USER_JSON"kubectl --kubeconfig <(echo $KUBECONFIG | base64 -d) exec solr-03bc977ae38d1796-solrcloud-0 --  curl \  -s -f -L \  -o /dev/null \  -w "%{http_code}\n" \  --user admin:${ADMIN_PASSWORD} \  'http://solr-03bc977ae38d1796-solrcloud-common/solr/admin/authorization' \  -H 'Content-type:application/json' --data "$SET_ROLE_JSON"': exit status 22. Output: Defaulted container "solrcloud-node" out of: solrcloud-node, cp-solr-xml (init), setup-zk (init)400command terminated with exit code 22Defaulted container "solrcloud-node" out of: solrcloud-node, cp-solr-xml (init), setup-zk (init)400command terminated with exit code 22 exit status 1
FAILED
```

I'm at a bit of a loss now, but I'll try to make sure that tests are passing locally at least.

**Comment by nickumia-reisys** [comment]
It just worked for me 😱 
image

I got the credentials and it it logged it properly...

**Comment by mogul** [comment]
We're now deploying the updated Solr brokerpak as a separate service-broker in parallel (`ssb-solrcloud` alongside `ssb-solr`). This should be safe to deploy now as it will leave the existing broker supporting inventory's Solr 6.6 in place.

**Comment by mogul** [comment]
PS: Note the updated plans above!
https://github.com/GSA/datagov-ssb/pull/112#issuecomment-1002641265

**Review by robert-bryson — APPROVED** [review]

**Pull request merged**
